# Generated by Django 4.1.7 on 2023-03-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=20, verbose_name="Название меню"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Use it in templatetag for displaying menu",
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        help_text="Named url from your urls.py file",
                        max_length=255,
                        verbose_name="Named URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название элемента"),
                ),
                (
                    "url",
                    models.CharField(blank=True, max_length=255, verbose_name="Ссылка"),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        help_text="Named url from your urls.py file",
                        max_length=255,
                        verbose_name="Named URL",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menu",
                        verbose_name="Элемент меню",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menuitem",
                        verbose_name="Верхний уровень меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент меню",
                "verbose_name_plural": "Элементы меню",
            },
        ),
    ]
